// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNyOoo4mKr-t_4Dr1wRTZilOBpVIUsSeY',
    appId: '1:157511563310:web:a131b862e85d292eadc7bf',
    messagingSenderId: '157511563310',
    projectId: 'admin-b58ff',
    authDomain: 'admin-b58ff.firebaseapp.com',
    storageBucket: 'admin-b58ff.appspot.com',
    measurementId: 'G-C1CQP6YNBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt6Gmt9c2LTOHrTe_mDFudVDwEjbcKvKI',
    appId: '1:157511563310:android:e3d606e7bec84638adc7bf',
    messagingSenderId: '157511563310',
    projectId: 'admin-b58ff',
    storageBucket: 'admin-b58ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBNjCfBb7gvOMRPNvAaqbD2zhBydUSSwA',
    appId: '1:157511563310:ios:380fc82a6292c031adc7bf',
    messagingSenderId: '157511563310',
    projectId: 'admin-b58ff',
    storageBucket: 'admin-b58ff.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBNjCfBb7gvOMRPNvAaqbD2zhBydUSSwA',
    appId: '1:157511563310:ios:e28b7a7c21ce8ab4adc7bf',
    messagingSenderId: '157511563310',
    projectId: 'admin-b58ff',
    storageBucket: 'admin-b58ff.appspot.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
